config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers:{
    registrations: 'registrations'
  }

  devise_scope :user do
    get '/login' => 'devise/sessions#new'
    get '/logout' => 'devise/sessions#destroy'
  end
  resources :user, :controller => "user"
    match 'user/:id' => 'user#destroy', :via => :delete, :as => :admin_destroy_user
    
  get 'home/index'

  get 'home/about'

  root 'home#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

    # Define abilities for the passed in user here. For example:
   def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
     user ||= User.new # guest user (not logged in)
    if user.has_role? :admin
       can :manage, :all
   elsif user.has_role? :author
        can :create, :all
        can :read, :all
        
    else
       can :read, :all
     end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable, :registerable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
    ROLES = %i[admin moderator author banned]
    def roles=(roles)
      roles = [*roles].map { |r| r.to_sym }
      self.roles_mask = (roles & ROLES).map { |r| 2**ROLES.index(r) }.inject(0, :+)
    end

    def roles
      ROLES.reject do |r|
        ((roles_mask.to_i || 0) & 2**ROLES.index(r)).zero?
      end
    end
  
    def has_role?(role)
        roles.include?(role)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_filter :configure_permitted_parameters, if: :devise_controller?
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
   rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_url, :alert => exception.message
  end
  protect_from_forgery with: :exception
   

       def configure_permitted_parameters
        devise_parameter_sanitizer.for(:sign_up) {|u| u.permit(:username, :first_name, :last_name, :email, :password, :password_confirmation,:remember_me, roles: [])}
        devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:username, :first_name, :last_name,:email, :password, :password_confirmation,:current_password, roles: [])}
        devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:username, :first_name, :last_name ,:email, :password, :remember_me) }
      end
      
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	@users = User.all
  end

  def about
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
 
  def update
    @user = User.find(params[:id])

    successfully_updated = if needs_password?(@user, params)
      @user.update_with_password(devise_parameter_sanitizer.sanitize(:account_update))
    else
      # remove the virtual current_password attribute
      # update_without_password doesn't know how to ignore it
      params[:user].delete(:current_password)
      @user.update_without_password(devise_parameter_sanitizer.sanitize(:account_update))
    end

    if successfully_updated
      set_flash_message :notice, :updated
      # Sign in the user bypassing validation in case their password changed
      sign_in @user, :bypass => true
      redirect_to user_path
    else
      render "edit"
    end
  end

  private

  # check if we need password to update user data
  # ie if password or email was changed
  # extend this as needed
  def needs_password?(user, params)
    user.email != params[:user][:email] ||
      params[:user][:password].present? ||
      params[:user][:password_confirmation].present?
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
	load_and_authorize_resource

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      flash[:notice] = "Successfully created User." 
      redirect_to root_path
    else
      render :action => 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

def update
  if params[:user][:password].blank?
      params[:user].delete("password")
      params[:user].delete("password_confirmation")
    end
    @user = User.find(params[:id])
    respond_to do |format|
      if @user.update(user_params)
          sign_in @user, :bypass => true
          format.html { redirect_to root_path, notice: 'user was successfully updated.' }
          format.json { head :no_content }
        else
          format.html { render action: 'edit' }
          format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
end
def destroy
    @user = User.find(params[:id])
    if @user.destroy
      flash[:notice] = "Successfully deleted User."
      redirect_to root_path
    end
end 

  # check if we need password to update user data
  # ie if password or email was changed
  # extend this as needed
def needs_password?(user, params)
  user.email != params[:user][:email] ||
    params[:user][:password].present? ||
    params[:user][:password_confirmation].present?
end

  private 
    def user_params
      params.require(:user).permit(:username, :first_name, :last_name,:email, :password, :password_confirmation,:current_password, roles: [])
     end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/home/about.html.erb
<h1>Home#about</h1>
<p>Find me in app/views/home/about.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pucsysmgm</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/user/_user_fields.html.erb
<p><%= f.label :first_name %></p>
<p><%= f.text_field :first_name %></p>
 
<p><%= f.label :last_name %></p>
<p><%= f.text_field :last_name %></p>
 
<p><%= f.label :email %></p>
<p><%= f.text_field :email %></p>

<% for role in User::ROLES %>
      <%= check_box_tag "user[roles][#{role}]", role, @user.roles.include?(role), {:name => "user[roles][]"}%>
        <%= label_tag "user_roles_#{role}", role.to_s.humanize %><br />
<% end %>
      <%= hidden_field_tag "user[roles][]", "" %>

app/views/user/edit.html.erb
<h3><%= @user == @current_user ? "Your Account Settings" : "Edit User" %></h3>
 
<%= form_for(@user, :html => { :method => :put }) do |f| %>
  <%= render :partial => 'user_fields', :locals => { :f => f } %>
 
  <p><%= f.label :password %> <i>(leave blank if you don't want to change it)</i></p>
  <p><%= f.password_field :password %></p>
 
  <p><%= f.label :password_confirmation %></p>
  <p><%= f.password_field :password_confirmation %></p>
 
  <p><%= f.submit "Update" %></p>
<% end %>
<%= link_to "Back", :back %>

app/views/user/index.html.erb
<% if can? :manage, @user%>
<%@users.each do |user| %>
	<%= user.email%> 
	<%= link_to 'Delete', admin_destroy_user_path(user), method: :delete, confirm: "Are you sure?" %>
	<%= link_to 'Edit', edit_user_path(user)%>
	<br>

<%end%>
<%end%>